version: "3.7"

services:

  app_proxy:
    environment:
      # Format: <app-id>_<docker-service-name>_1
      APP_HOST: thcabinets-splash_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/devcal1/thcabinets-web:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/uploads:/app/uploads
      - ${APP_DATA_DIR}/data/db:/app/db
      - ${APP_DATA_DIR}/data/config:/app/config
